name: Setup Node.js and pnpm
description: Sets up Node.js and pnpm with caching
inputs:
  install-deps:
    description: Whether to install dependencies with pnpm
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1.0.0
      with:
        cache: true
        runtime: node@24.19.0
        install: ${{ inputs.install-deps }}
      env:
        HUSKY: 0
