name: Setup Node.js and pnpm
description: Sets up Node.js and pnpm with caching
inputs:
  install-deps:
    description: Whether to install dependencies with pnpm
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
      with:
        cache: true
        install: ${{ inputs.install-deps }}
      env:
        HUSKY: 0
