export const button = {
  root: {
    iconOnlyWidth: "2.5rem",
    borderRadius: "{form.field.border.radius}",
    roundedBorderRadius: "2rem",
    gap: "0.5rem",
    paddingX: "{form.field.padding.x}",
    paddingY: "{form.field.padding.y}",
    sm: {
      fontSize: "{form.field.sm.font.size}",
      paddingX: "{form.field.sm.padding.x}",
      paddingY: "{form.field.sm.padding.y}",
    },
    lg: {
      fontSize: "{form.field.lg.font.size}",
      paddingX: "{form.field.lg.padding.x}",
      paddingY: "{form.field.lg.padding.y}",
    },
    label: { fontWeight: "400" },
    raisedShadow: "0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12)",
    focusRing: {
      width: "{focus.ring.width}",
      style: "{focus.ring.style}",
      offset: "{focus.ring.offset}",
    },
    badgeSize: "1rem",
    transitionDuration: "{form.field.transition.duration}",
  },
  colorScheme: {
    light: {
      root: {
        primary: {
          background: "{primary.color}",
          hoverBackground: "{primary.hover.color}",
          activeBackground: "{primary.active.color}",
          borderColor: "{primary.color}",
          hoverBorderColor: "{primary.hover.color}",
          activeBorderColor: "{primary.active.color}",
          color: "{primary.contrast.color}",
          hoverColor: "{primary.contrast.color}",
          activeColor: "{primary.contrast.color}",
          focusRing: { color: "{primary.color}", shadow: "none" },
        },
        secondary: {
          background: "{surface.100}",
          hoverBackground: "{surface.200}",
          activeBackground: "{surface.300}",
          borderColor: "{surface.100}",
          hoverBorderColor: "{surface.200}",
          activeBorderColor: "{surface.300}",
          color: "{surface.600}",
          hoverColor: "{surface.700}",
          activeColor: "{surface.800}",
          focusRing: { color: "{surface.600}", shadow: "none" },
        },
        info: {
          background: "{sky.500}",
          hoverBackground: "{sky.600}",
          activeBackground: "{sky.700}",
          borderColor: "{sky.500}",
          hoverBorderColor: "{sky.600}",
          activeBorderColor: "{sky.700}",
          color: "#ffffff",
          hoverColor: "#ffffff",
          activeColor: "#ffffff",
          focusRing: { color: "{sky.500}", shadow: "none" },
        },
        success: {
          background: "{green.500}",
          hoverBackground: "{green.600}",
          activeBackground: "{green.700}",
          borderColor: "{green.500}",
          hoverBorderColor: "{green.600}",
          activeBorderColor: "{green.700}",
          color: "#ffffff",
          hoverColor: "#ffffff",
          activeColor: "#ffffff",
          focusRing: { color: "{green.500}", shadow: "none" },
        },
        warn: {
          background: "{orange.500}",
          hoverBackground: "{orange.600}",
          activeBackground: "{orange.700}",
          borderColor: "{orange.500}",
          hoverBorderColor: "{orange.600}",
          activeBorderColor: "{orange.700}",
          color: "#ffffff",
          hoverColor: "#ffffff",
          activeColor: "#ffffff",
          focusRing: { color: "{orange.500}", shadow: "none" },
        },
        help: {
          background: "{purple.500}",
          hoverBackground: "{purple.600}",
          activeBackground: "{purple.700}",
          borderColor: "{purple.500}",
          hoverBorderColor: "{purple.600}",
          activeBorderColor: "{purple.700}",
          color: "#ffffff",
          hoverColor: "#ffffff",
          activeColor: "#ffffff",
          focusRing: { color: "{purple.500}", shadow: "none" },
        },
        danger: {
          background: "{red.500}",
          hoverBackground: "{red.600}",
          activeBackground: "{red.700}",
          borderColor: "{red.500}",
          hoverBorderColor: "{red.600}",
          activeBorderColor: "{red.700}",
          color: "#ffffff",
          hoverColor: "#ffffff",
          activeColor: "#ffffff",
          focusRing: { color: "{red.500}", shadow: "none" },
        },
        contrast: {
          background: "{surface.950}",
          hoverBackground: "{surface.900}",
          activeBackground: "{surface.800}",
          borderColor: "{surface.950}",
          hoverBorderColor: "{surface.900}",
          activeBorderColor: "{surface.800}",
          color: "{surface.0}",
          hoverColor: "{surface.0}",
          activeColor: "{surface.0}",
          focusRing: { color: "{surface.950}", shadow: "none" },
        },
      },
      outlined: {
        primary: {
          color: "{primary.color}",
          borderColor: "{primary.200}",
          hoverBackground: "{primary.50}",
          activeBackground: "{primary.100}",
        },
        secondary: {
          color: "{surface.500}",
          borderColor: "{surface.200}",
          hoverBackground: "{surface.50}",
          activeBackground: "{surface.100}",
        },
        success: {
          color: "{green.500}",
          borderColor: "{green.200}",
          hoverBackground: "{green.50}",
          activeBackground: "{green.100}",
        },
        info: {
          color: "{sky.500}",
          borderColor: "{sky.200}",
          hoverBackground: "{sky.50}",
          activeBackground: "{sky.100}",
        },
        warn: {
          color: "{orange.500}",
          borderColor: "{orange.200}",
          hoverBackground: "{orange.50}",
          activeBackground: "{orange.100}",
        },
        help: {
          color: "{purple.500}",
          borderColor: "{purple.200}",
          hoverBackground: "{purple.50}",
          activeBackground: "{purple.100}",
        },
        danger: {
          color: "{red.500}",
          borderColor: "{red.200}",
          hoverBackground: "{red.50}",
          activeBackground: "{red.100}",
        },
        contrast: {
          color: "{surface.950}",
          borderColor: "{surface.700}",
          hoverBackground: "{surface.50}",
          activeBackground: "{surface.100}",
        },
      },
      text: {
        primary: {
          color: "{primary.color}",
          hoverBackground: "{primary.50}",
          activeBackground: "{primary.100}",
        },
        secondary: {
          color: "{surface.500}",
          hoverBackground: "{surface.50}",
          activeBackground: "{surface.100}",
        },
        success: {
          color: "{green.500}",
          hoverBackground: "{green.50}",
          activeBackground: "{green.100}",
        },
        info: {
          color: "{sky.500}",
          hoverBackground: "{sky.50}",
          activeBackground: "{sky.100}",
        },
        warn: {
          color: "{orange.500}",
          hoverBackground: "{orange.50}",
          activeBackground: "{orange.100}",
        },
        help: {
          color: "{purple.500}",
          hoverBackground: "{purple.50}",
          activeBackground: "{purple.100}",
        },
        danger: {
          color: "{red.500}",
          hoverBackground: "{red.50}",
          activeBackground: "{red.100}",
        },
        contrast: {
          color: "{surface.950}",
          hoverBackground: "{surface.50}",
          activeBackground: "{surface.100}",
        },
      },
      link: {
        color: "{primary.color}",
        hoverColor: "{primary.color}",
        activeColor: "{primary.color}",
      },
    },
    dark: {
      root: {
        primary: {
          background: "{primary.color}",
          hoverBackground: "{primary.hover.color}",
          activeBackground: "{primary.active.color}",
          borderColor: "{primary.color}",
          hoverBorderColor: "{primary.hover.color}",
          activeBorderColor: "{primary.active.color}",
          color: "{primary.contrast.color}",
          hoverColor: "{primary.contrast.color}",
          activeColor: "{primary.contrast.color}",
          focusRing: { color: "{primary.color}", shadow: "none" },
        },
        secondary: {
          background: "{surface.600}",
          hoverBackground: "{surface.500}",
          activeBackground: "{surface.400}",
          borderColor: "{surface.600}",
          hoverBorderColor: "{surface.500}",
          activeBorderColor: "{surface.400}",
          color: "{text.color}",
          hoverColor: "{text.color}",
          activeColor: "{text.color}",
          focusRing: { color: "{surface.600}", shadow: "none" },
        },
        info: {
          background: "{info.color}",
          hoverBackground: "{info.hover.color}",
          activeBackground: "{info.active.color}",
          borderColor: "{info.color}",
          hoverBorderColor: "{info.hover.color}",
          activeBorderColor: "{info.active.color}",
          color: "{info.contrast.color}",
          hoverColor: "{info.contrast.color}",
          activeColor: "{info.contrast.color}",
          focusRing: { color: "{info.color}", shadow: "none" },
        },
        success: {
          background: "{success.color}",
          hoverBackground: "{success.hover.color}",
          activeBackground: "{success.active.color}",
          borderColor: "{success.color}",
          hoverBorderColor: "{success.hover.color}",
          activeBorderColor: "{success.active.color}",
          color: "{success.contrast.color}",
          hoverColor: "{success.contrast.color}",
          activeColor: "{success.contrast.color}",
          focusRing: { color: "{success.color}", shadow: "none" },
        },
        warn: {
          background: "{warn.color}",
          hoverBackground: "{warn.hover.color}",
          activeBackground: "{warn.active.color}",
          borderColor: "{warn.color}",
          hoverBorderColor: "{warn.hover.color}",
          activeBorderColor: "{warn.active.color}",
          color: "{warn.contrast.color}",
          hoverColor: "{warn.contrast.color}",
          activeColor: "{warn.contrast.color}",
          focusRing: { color: "{warn.color}", shadow: "none" },
        },
        help: {
          background: "{help.color}",
          hoverBackground: "{help.hover.color}",
          activeBackground: "{help.active.color}",
          borderColor: "{help.color}",
          hoverBorderColor: "{help.hover.color}",
          activeBorderColor: "{help.active.color}",
          color: "{help.contrast.color}",
          hoverColor: "{help.contrast.color}",
          activeColor: "{help.contrast.color}",
          focusRing: { color: "{help.color}", shadow: "none" },
        },
        danger: {
          background: "{danger.color}",
          hoverBackground: "{danger.hover.color}",
          activeBackground: "{danger.active.color}",
          borderColor: "{danger.color}",
          hoverBorderColor: "{danger.hover.color}",
          activeBorderColor: "{danger.active.color}",
          color: "{danger.contrast.color}",
          hoverColor: "{danger.contrast.color}",
          activeColor: "{danger.contrast.color}",
          focusRing: { color: "{danger.color}", shadow: "none" },
        },
        contrast: {
          background: "{text.color}",
          hoverBackground: "{text.hover.color}",
          activeBackground: "{text.active.color}",
          borderColor: "{text.color}",
          hoverBorderColor: "{text.hover.color}",
          activeBorderColor: "{text.active.color}",
          color: "{text.contrast.color}",
          hoverColor: "{text.contrast.color}",
          activeColor: "{text.contrast.color}",
          focusRing: { color: "{text.color}", shadow: "none" },
        },
      },
      outlined: {
        primary: {
          color: "{primary.color}",
          borderColor: "{primary.color}",
          hoverBackground: "color-mix(in srgb, {primary.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {primary.color}, transparent 84%)",
        },
        secondary: {
          color: "{text.color}",
          borderColor: "{surface.400}",
          hoverBackground: "color-mix(in srgb, {text.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {text.color}, transparent 84%)",
        },
        success: {
          color: "{success.color}",
          borderColor: "{success.color}",
          hoverBackground: "color-mix(in srgb, {success.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {success.color}, transparent 84%)",
        },
        info: {
          color: "{info.color}",
          borderColor: "{info.color}",
          hoverBackground: "color-mix(in srgb, {info.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {info.color}, transparent 84%)",
        },
        warn: {
          color: "{warn.color}",
          borderColor: "{warn.color}",
          hoverBackground: "color-mix(in srgb, {warn.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {warn.color}, transparent 84%)",
        },
        help: {
          color: "{help.color}",
          borderColor: "{help.color}",
          hoverBackground: "color-mix(in srgb, {help.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {help.color}, transparent 84%)",
        },
        danger: {
          color: "{danger.color}",
          borderColor: "{danger.color}",
          hoverBackground: "color-mix(in srgb, {danger.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {danger.color}, transparent 84%)",
        },
        contrast: {
          color: "{text.color}",
          borderColor: "{text.color}",
          hoverBackground: "color-mix(in srgb, {text.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {text.color}, transparent 84%)",
        },
      },
      text: {
        primary: {
          color: "{primary.color}",
          hoverBackground: "color-mix(in srgb, {primary.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {primary.color}, transparent 84%)",
        },
        secondary: {
          color: "{text.color}",
          hoverBackground: "color-mix(in srgb, {text.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {text.color}, transparent 84%)",
        },
        success: {
          color: "{success.color}",
          hoverBackground: "color-mix(in srgb, {success.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {success.color}, transparent 84%)",
        },
        info: {
          color: "{info.color}",
          hoverBackground: "color-mix(in srgb, {info.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {info.color}, transparent 84%)",
        },
        warn: {
          color: "{warn.color}",
          hoverBackground: "color-mix(in srgb, {warn.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {warn.color}, transparent 84%)",
        },
        help: {
          color: "{help.color}",
          hoverBackground: "color-mix(in srgb, {help.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {help.color}, transparent 84%)",
        },
        danger: {
          color: "{danger.color}",
          hoverBackground: "color-mix(in srgb, {danger.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {danger.color}, transparent 84%)",
        },
        contrast: {
          color: "{text.color}",
          hoverBackground: "color-mix(in srgb, {text.color}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {text.color}, transparent 84%)",
        },
      },
      link: {
        color: "{primary.color}",
        hoverColor: "{primary.hover.color}",
        activeColor: "{primary.active.color}",
      },
    },
  },
};
