export const semantic = {
  transitionDuration: "0.2s",
  focusRing: {
    width: "1px",
    style: "solid",
    color: "{primary.color}",
    offset: "2px",
    shadow: "none",
  },
  disabledOpacity: "0.6",
  iconSize: "1rem",
  anchorGutter: "2px",
  formField: {
    paddingX: "0.625rem",
    paddingY: "0.5rem",
    sm: {
      fontSize: "0.875rem",
      paddingX: "0.5rem",
      paddingY: "0.375rem",
    },
    lg: {
      fontSize: "1.125rem",
      paddingX: "0.75rem",
      paddingY: "0.625rem",
    },
    borderRadius: "{border.radius.md}",
    focusRing: {
      width: "0",
      style: "none",
      color: "transparent",
      offset: "0",
      shadow: "none",
    },
    transitionDuration: "{transition.duration}",
  },
  list: {
    padding: "0.25rem 0.25rem",
    gap: "2px",
    header: { padding: "0.5rem 1rem 0.25rem 1rem" },
    option: { padding: "0.5rem 0.75rem", borderRadius: "{border.radius.sm}" },
    optionGroup: { padding: "0.5rem 0.75rem", fontWeight: "600" },
  },
  content: { borderRadius: "{border.radius.md}" },
  mask: { transitionDuration: "0.15s" },
  navigation: {
    list: { padding: "0.25rem 0.25rem", gap: "0.125rem" },
    item: { padding: "0.375rem 0.5rem", borderRadius: "{border.radius.sm}", gap: "0.5rem" },
    submenuLabel: { padding: "0.5rem 0.75rem", fontWeight: "600" },
    submenuIcon: { size: "0.875rem" },
  },
  overlay: {
    select: {
      borderRadius: "{border.radius.md}",
      shadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)",
    },
    popover: {
      borderRadius: "{border.radius.md}",
      padding: "0.75rem",
      shadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)",
    },
    modal: {
      borderRadius: "{border.radius.xl}",
      padding: "1.25rem",
      shadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)",
    },
    navigation: { shadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)" },
  },
  colorScheme: {
    light: {
      surface: {
        50: "#f9fafb",
        100: "#f5f7f9",
        200: "#f2f4f8",
        300: "#eff1f6",
        400: "#eceff4",
        500: "#e5e9f0",
        600: "#d8dee9",
        700: "#bec8da",
        800: "#9dacc8",
        900: "#768bb2",
        950: "#5c75a3",
      },
      primary: {
        color: "{primary.500}",
        contrastColor: "{text.contrast.color}",
        hoverColor: "{primary.600}",
        activeColor: "{primary.700}",
        text: {
          color: "{primary.700}",
          hoverColor: "{primary.800}",
          activeColor: "{primary.900}",
        },
      },
      danger: {
        color: "{danger.500}",
        contrastColor: "{text.contrast.color}",
        hoverColor: "{danger.600}",
        activeColor: "{danger.700}",
      },
      warn: {
        color: "{warn.500}",
        contrastColor: "{text.contrast.color}",
        hoverColor: "{warn.600}",
        activeColor: "{warn.700}",
      },
      success: {
        color: "{success.500}",
        contrastColor: "{text.contrast.color}",
        hoverColor: "{success.600}",
        activeColor: "{success.700}",
      },
      info: {
        color: "{info.500}",
        contrastColor: "{text.contrast.color}",
        hoverColor: "{info.600}",
        activeColor: "{info.700}",
      },
      help: {
        color: "{help.500}",
        contrastColor: "{text.contrast.color}",
        hoverColor: "{help.600}",
        activeColor: "{help.700}",
      },
      highlight: {
        background: "{surface.600}",
        focusBackground: "{primary.color}",
        color: "{text.color}",
        focusColor: "{text.color}",
      },
      mask: { background: "rgba(0, 0, 0, 0.4)", color: "{surface.200}" },
      formField: {
        background: "{content.background}",
        disabledBackground: "{content.hover.background}",
        filledBackground: "{surface.50}",
        filledHoverBackground: "{surface.50}",
        filledFocusBackground: "{surface.50}",
        borderColor: "{content.border.color}",
        hoverBorderColor: "{content.border.color}",
        focusBorderColor: "{primary.color}",
        invalidBorderColor: "{danger.color}",
        color: "{text.color}",
        disabledColor: "{surface.700}",
        placeholderColor: "{surface.600}",
        invalidPlaceholderColor: "{danger.color}",
        floatLabelColor: "{text.muted.color}",
        floatLabelFocusColor: "{primary.text.color}",
        floatLabelActiveColor: "{text.hover.muted.color}",
        floatLabelInvalidColor: "{danger.color}",
        iconColor: "{text.color}",
        shadow: "0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)",
      },
      text: {
        color: "#2e3440",
        contrastColor: "{surface.400}",
        hoverColor: "#3b4252",
        activeColor: "#434c5e",
        mutedColor: "{text.active.color}",
        hoverMutedColor: "{text.hover.color}",
        activeMutedColor: "{text.color}",
      },
      content: {
        background: "{surface.400}",
        hoverBackground: "{surface.500}",
        borderColor: "{surface.600}",
        color: "{text.color}",
        hoverColor: "{text.hover.color}",
      },
      overlay: {
        select: {
          background: "{content.hover.background}",
          borderColor: "{content.border.color}",
          color: "{text.color}",
        },
        popover: {
          background: "{surface.600}",
          borderColor: "{surface.700}",
          color: "{text.color}",
        },
        modal: {
          background: "{content.background}",
          borderColor: "{content.border.color}",
          color: "{text.color}",
        },
      },
      list: {
        option: {
          focusBackground: "{primary.color}",
          selectedBackground: "{highlight.background}",
          selectedFocusBackground: "{highlight.focus.background}",
          color: "{text.color}",
          focusColor: "{text.color}",
          selectedColor: "{highlight.color}",
          selectedFocusColor: "{highlight.focus.color}",
          icon: {
            color: "{text.color}",
            focusColor: "{text.color}",
          },
        },
        optionGroup: {
          background: "transparent",
          color: "{text.muted.color}",
        },
      },
      navigation: {
        item: {
          focusBackground: "{primary.color}",
          activeBackground: "{primary.color}",
          color: "{text.color}",
          focusColor: "{text.color}",
          activeColor: "{text.color}",
          icon: {
            color: "{text.color}",
            focusColor: "{text.color}",
            activeColor: "{text.color}",
          },
        },
        submenuLabel: {
          background: "transparent",
          color: "{text.muted.color}",
        },
        submenuIcon: {
          color: "{text.color}",
          focusColor: "{text.color}",
          activeColor: "{text.color}",
        },
      },
    },
    dark: {
      surface: {
        50: "#e4e7ec",
        100: "#d5d9e1",
        200: "#b5bcca",
        300: "#8893aa",
        400: "#4c566a",
        500: "#434c5e",
        600: "#3b4252",
        700: "#2e3440",
        800: "#2b303b",
        900: "#22272f",
        950: "#171b21",
      },
      primary: {
        color: "{primary.500}",
        contrastColor: "{text.contrast.color}",
        hoverColor: "{primary.400}",
        activeColor: "{primary.300}",
        text: {
          color: "{primary.color}",
          hoverColor: "{primary.hover.color}",
          activeColor: "{primary.active.color}",
        },
      },
      danger: {
        color: "{danger.500}",
        contrastColor: "{text.contrast.color}",
        hoverColor: "{danger.400}",
        activeColor: "{danger.300}",
      },
      warn: {
        color: "{warn.500}",
        contrastColor: "{text.contrast.color}",
        hoverColor: "{warn.400}",
        activeColor: "{warn.300}",
      },
      success: {
        color: "{success.500}",
        contrastColor: "{text.contrast.color}",
        hoverColor: "{success.400}",
        activeColor: "{success.300}",
      },
      info: {
        color: "{info.500}",
        contrastColor: "{text.contrast.color}",
        hoverColor: "{info.400}",
        activeColor: "{info.300}",
      },
      help: {
        color: "{help.500}",
        contrastColor: "{text.contrast.color}",
        hoverColor: "{help.400}",
        activeColor: "{help.300}",
      },
      highlight: {
        background: "{content.hover.background}",
        focusBackground: "{primary.color}",
        color: "{text.color}",
        focusColor: "{text.contrast.color}",
      },
      mask: { background: "rgba(0, 0, 0, 0.6)", color: "{surface.200}" },
      formField: {
        background: "{content.hover.background}",
        disabledBackground: "{content.background}",
        filledBackground: "{surface.800}",
        filledHoverBackground: "{surface.800}",
        filledFocusBackground: "{surface.800}",
        borderColor: "{content.border.color}",
        hoverBorderColor: "{content.border.color}",
        focusBorderColor: "{primary.color}",
        invalidBorderColor: "{danger.color}",
        color: "{text.color}",
        disabledColor: "{surface.400}",
        placeholderColor: "{surface.400}",
        invalidPlaceholderColor: "{danger.color}",
        floatLabelColor: "{text.muted.color}",
        floatLabelFocusColor: "{primary.text.color}",
        floatLabelActiveColor: "{text.hover.muted.color}",
        floatLabelInvalidColor: "{danger.color}",
        iconColor: "{text.color}",
        shadow: "0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)",
      },
      text: {
        color: "#eceff4",
        contrastColor: "{surface.700}",
        hoverColor: "#e5e9f0",
        activeColor: "#d8dee9",
        mutedColor: "{text.active.color}",
        hoverMutedColor: "{text.hover.color}",
        activeMutedColor: "{text.color}",
      },
      content: {
        background: "{surface.700}",
        hoverBackground: "{surface.600}",
        borderColor: "{surface.500}",
        color: "{text.color}",
        hoverColor: "{text.hover.color}",
      },
      overlay: {
        select: {
          background: "{surface.900}",
          borderColor: "{content.border.color}",
          color: "{text.color}",
        },
        popover: {
          background: "{surface.900}",
          borderColor: "{content.border.color}",
          color: "{text.color}",
        },
        modal: {
          background: "{content.background}",
          borderColor: "{content.border.color}",
          color: "{text.color}",
        },
      },
      list: {
        option: {
          focusBackground: "{primary.color}",
          selectedBackground: "{highlight.background}",
          selectedFocusBackground: "{highlight.focus.background}",
          color: "{text.color}",
          focusColor: "{text.contrast.color}",
          selectedColor: "{highlight.color}",
          selectedFocusColor: "{highlight.focus.color}",
          icon: {
            color: "{text.color}",
            focusColor: "{text.color}",
          },
        },
        optionGroup: {
          background: "transparent",
          color: "{text.muted.color}",
        },
      },
      navigation: {
        item: {
          focusBackground: "{primary.color}",
          activeBackground: "{primary.color}",
          color: "{text.color}",
          focusColor: "{text.contrast.color}",
          activeColor: "{text.contrast.color}",
          icon: {
            color: "{text.color}",
            focusColor: "{text.contrast.color}",
            activeColor: "{text.contrast.color}",
          },
        },
        submenuLabel: {
          background: "transparent",
          color: "{text.muted.color}",
        },
        submenuIcon: {
          color: "{text.color}",
          focusColor: "{text.contrast.color}",
          activeColor: "{text.contrast.color}",
        },
      },
    },
  },
};
