export const toggleswitch = {
  root: {
    width: "2.5rem",
    height: "1.5rem",
    borderRadius: "30px",
    gap: "0.25rem",
    shadow: "{form.field.shadow}",
    focusRing: {
      width: "{focus.ring.width}",
      style: "{focus.ring.style}",
      color: "{focus.ring.color}",
      offset: "{focus.ring.offset}",
      shadow: "{focus.ring.shadow}",
    },
    borderWidth: "1px",
    borderColor: "transparent",
    hoverBorderColor: "transparent",
    checkedBorderColor: "transparent",
    checkedHoverBorderColor: "transparent",
    invalidBorderColor: "{form.field.invalid.border.color}",
    transitionDuration: "{form.field.transition.duration}",
    slideDuration: "0.2s",
  },
  handle: { borderRadius: "50%", size: "1rem" },
  colorScheme: {
    light: {
      root: {
        background: "{surface.700}",
        disabledBackground: "{surface.600}",
        hoverBackground: "{surface.700}",
        checkedBackground: "{primary.color}",
        checkedHoverBackground: "{primary.color}",
      },
      handle: {
        background: "{surface.400}",
        disabledBackground: "{surface.400}",
        hoverBackground: "{surface.400}",
        checkedBackground: "{surface.400}",
        checkedHoverBackground: "{surface.400}",
        color: "{text.color}",
        hoverColor: "{text.color}",
        checkedColor: "{primary.color}",
        checkedHoverColor: "{primary.color}",
      },
    },
    dark: {
      root: {
        background: "{form.field.background}",
        disabledBackground: "{form.field.background}",
        hoverBackground: "{form.field.background}",
        checkedBackground: "{primary.color}",
        checkedHoverBackground: "{primary.color}",
      },
      handle: {
        background: "{surface.900}",
        disabledBackground: "{surface.400}",
        hoverBackground: "{surface.900}",
        checkedBackground: "{surface.900}",
        checkedHoverBackground: "{surface.900}",
        color: "{surface.900}",
        hoverColor: "{surface.900}",
        checkedColor: "{primary.color}",
        checkedHoverColor: "{primary.color}",
      },
    },
  },
};
