name: CI (backend)
on:
  pull_request:
    branches: [main, dev]
    types: [opened, reopened, edited, synchronize]
    paths:
      - "app/src-tauri/**"
      - "app/src-wasm/**"
      - "crates/**"
      - "packages/*/src-wasm/**"
      - "Cargo.*"
      - rustfmt.toml
      - clippy.toml
      - .github/workflows/ci.backend.yml
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}-backend
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-rust
        with:
          stable-components: clippy
          nightly-components: rustfmt
      - run: cargo +nightly fmt --check
      - run: cargo clippy --locked -- -D warnings
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-rust
        with:
          tools: cargo-nextest
      - run: cargo nextest run --locked
