name: CI (frontend)
on:
  pull_request:
    branches: [main, dev]
    types: [opened, reopened, edited, synchronize]
    paths:
      - "app/**"
      - "!app/src-tauri/**"
      - "!app/src-wasm/**"
      - "docs/**"
      - "packages/**"
      - "!packages/*/src-wasm/**"
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - eslint.config.js
      - .markdownlint-cli2.jsonc
      - .oxfmtrc.json
      - .oxlintrc.json
      - .github/workflows/ci.frontend.yml
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}-frontend
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-node
      - run: pnpm fmt
      - run: pnpm lint

  # We intentionally run only unit tests, as we were unsuccessfull in achieving 100% match between local and CI snapshots for component tests.
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-node
      - run: pnpm test:unit
