name: CI (integration)
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}-integration
  cancel-in-progress: true
jobs:
  test-e2e-desktop-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-rust
        with:
          tools: tauri-driver

      - name: Install system webdriver
        run: sudo apt-get install -y webkit2gtk-driver xvfb xdg-user-dirs

      - name: Run tests
        run: |
          xdg-user-dirs-update
          source ${HOME}/.config/user-dirs.dirs
          xvfb-run pnpm --filter @embroiderly/app test:e2e:desktop

  test-e2e-desktop-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-rust
        with:
          tools: tauri-driver

      - name: Install system webdriver
        run: cargo install --git https://github.com/chippers/msedgedriver-tool

      - name: Run tests
        run: pnpm --filter @embroiderly/app test:e2e:desktop

  test-e2e-web-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-rust
        with:
          targets: wasm32-unknown-unknown
          tools: wasm-pack

      - name: Run tests
        run: pnpm --filter @embroiderly/app test:e2e:web

  test-e2e-web-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-rust
        with:
          targets: wasm32-unknown-unknown
          tools: wasm-pack

      - name: Run tests
        run: pnpm --filter @embroiderly/app test:e2e:web
